// ISO 4217 currency codes/names are real, standard reference data. The
// exchange rates are illustrative mock values (USD as base = 1) — there's
// no live FX feed here, consistent with the rest of this page's pricing.
export interface Currency {
  code: string;
  name: string;
  rateFromUsd: number;
}

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", rateFromUsd: 1 },
  { code: "EUR", name: "Euro", rateFromUsd: 0.92 },
  { code: "GBP", name: "British Pound", rateFromUsd: 0.78 },
  { code: "JPY", name: "Japanese Yen", rateFromUsd: 149 },
  { code: "CHF", name: "Swiss Franc", rateFromUsd: 0.88 },
  { code: "CAD", name: "Canadian Dollar", rateFromUsd: 1.36 },
  { code: "AUD", name: "Australian Dollar", rateFromUsd: 1.52 },
  { code: "NZD", name: "New Zealand Dollar", rateFromUsd: 1.64 },
  { code: "CNY", name: "Chinese Yuan", rateFromUsd: 7.2 },
  { code: "HKD", name: "Hong Kong Dollar", rateFromUsd: 7.8 },
  { code: "SGD", name: "Singapore Dollar", rateFromUsd: 1.34 },
  { code: "INR", name: "Indian Rupee", rateFromUsd: 83.3 },
  { code: "IDR", name: "Indonesian Rupiah", rateFromUsd: 15800 },
  { code: "MYR", name: "Malaysian Ringgit", rateFromUsd: 4.4 },
  { code: "THB", name: "Thai Baht", rateFromUsd: 34.5 },
  { code: "PHP", name: "Philippine Peso", rateFromUsd: 56.8 },
  { code: "VND", name: "Vietnamese Dong", rateFromUsd: 25400 },
  { code: "KRW", name: "South Korean Won", rateFromUsd: 1330 },
  { code: "TWD", name: "New Taiwan Dollar", rateFromUsd: 31.5 },
  { code: "PKR", name: "Pakistani Rupee", rateFromUsd: 278 },
  { code: "BDT", name: "Bangladeshi Taka", rateFromUsd: 118 },
  { code: "LKR", name: "Sri Lankan Rupee", rateFromUsd: 300 },
  { code: "NPR", name: "Nepalese Rupee", rateFromUsd: 133 },
  { code: "MMK", name: "Myanmar Kyat", rateFromUsd: 2100 },
  { code: "KHR", name: "Cambodian Riel", rateFromUsd: 4080 },
  { code: "LAK", name: "Lao Kip", rateFromUsd: 21500 },
  { code: "BND", name: "Brunei Dollar", rateFromUsd: 1.34 },
  { code: "MNT", name: "Mongolian Tugrik", rateFromUsd: 3450 },
  { code: "KZT", name: "Kazakhstani Tenge", rateFromUsd: 445 },
  { code: "UZS", name: "Uzbekistani Som", rateFromUsd: 12700 },
  { code: "KGS", name: "Kyrgyzstani Som", rateFromUsd: 87.5 },
  { code: "TJS", name: "Tajikistani Somoni", rateFromUsd: 10.9 },
  { code: "TMT", name: "Turkmenistani Manat", rateFromUsd: 3.5 },
  { code: "AZN", name: "Azerbaijani Manat", rateFromUsd: 1.7 },
  { code: "GEL", name: "Georgian Lari", rateFromUsd: 2.65 },
  { code: "AMD", name: "Armenian Dram", rateFromUsd: 388 },
  { code: "BYN", name: "Belarusian Ruble", rateFromUsd: 3.25 },
  { code: "RUB", name: "Russian Ruble", rateFromUsd: 92 },
  { code: "UAH", name: "Ukrainian Hryvnia", rateFromUsd: 41.2 },
  { code: "MDL", name: "Moldovan Leu", rateFromUsd: 17.8 },
  { code: "RON", name: "Romanian Leu", rateFromUsd: 4.58 },
  { code: "BGN", name: "Bulgarian Lev", rateFromUsd: 1.8 },
  { code: "HUF", name: "Hungarian Forint", rateFromUsd: 358 },
  { code: "PLN", name: "Polish Zloty", rateFromUsd: 4.0 },
  { code: "CZK", name: "Czech Koruna", rateFromUsd: 22.7 },
  { code: "SEK", name: "Swedish Krona", rateFromUsd: 10.4 },
  { code: "NOK", name: "Norwegian Krone", rateFromUsd: 10.6 },
  { code: "DKK", name: "Danish Krone", rateFromUsd: 6.86 },
  { code: "ISK", name: "Icelandic Krona", rateFromUsd: 138 },
  { code: "TRY", name: "Turkish Lira", rateFromUsd: 32.1 },
  { code: "ILS", name: "Israeli New Shekel", rateFromUsd: 3.7 },
  { code: "JOD", name: "Jordanian Dinar", rateFromUsd: 0.709 },
  { code: "LBP", name: "Lebanese Pound", rateFromUsd: 89500 },
  { code: "SYP", name: "Syrian Pound", rateFromUsd: 13000 },
  { code: "IQD", name: "Iraqi Dinar", rateFromUsd: 1310 },
  { code: "IRR", name: "Iranian Rial", rateFromUsd: 42000 },
  { code: "AFN", name: "Afghan Afghani", rateFromUsd: 70 },
  { code: "SAR", name: "Saudi Riyal", rateFromUsd: 3.75 },
  { code: "AED", name: "UAE Dirham", rateFromUsd: 3.67 },
  { code: "QAR", name: "Qatari Riyal", rateFromUsd: 3.64 },
  { code: "OMR", name: "Omani Rial", rateFromUsd: 0.385 },
  { code: "BHD", name: "Bahraini Dinar", rateFromUsd: 0.376 },
  { code: "KWD", name: "Kuwaiti Dinar", rateFromUsd: 0.307 },
  { code: "YER", name: "Yemeni Rial", rateFromUsd: 250 },
  { code: "EGP", name: "Egyptian Pound", rateFromUsd: 48.5 },
  { code: "LYD", name: "Libyan Dinar", rateFromUsd: 4.85 },
  { code: "TND", name: "Tunisian Dinar", rateFromUsd: 3.1 },
  { code: "DZD", name: "Algerian Dinar", rateFromUsd: 134.5 },
  { code: "MAD", name: "Moroccan Dirham", rateFromUsd: 9.95 },
  { code: "MRU", name: "Mauritanian Ouguiya", rateFromUsd: 39.8 },
  { code: "XOF", name: "West African CFA Franc", rateFromUsd: 605 },
  { code: "XAF", name: "Central African CFA Franc", rateFromUsd: 605 },
  { code: "GHS", name: "Ghanaian Cedi", rateFromUsd: 15.7 },
  { code: "NGN", name: "Nigerian Naira", rateFromUsd: 1550 },
  { code: "GMD", name: "Gambian Dalasi", rateFromUsd: 68 },
  { code: "GNF", name: "Guinean Franc", rateFromUsd: 8600 },
  { code: "SLE", name: "Sierra Leonean Leone", rateFromUsd: 22.7 },
  { code: "LRD", name: "Liberian Dollar", rateFromUsd: 193 },
  { code: "CVE", name: "Cape Verdean Escudo", rateFromUsd: 101 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", rateFromUsd: 22.3 },
  { code: "XPF", name: "CFP Franc", rateFromUsd: 110 },
  { code: "ZAR", name: "South African Rand", rateFromUsd: 18.2 },
  { code: "NAD", name: "Namibian Dollar", rateFromUsd: 18.2 },
  { code: "BWP", name: "Botswana Pula", rateFromUsd: 13.6 },
  { code: "ZMW", name: "Zambian Kwacha", rateFromUsd: 26.5 },
  { code: "MWK", name: "Malawian Kwacha", rateFromUsd: 1735 },
  { code: "MZN", name: "Mozambican Metical", rateFromUsd: 63.9 },
  { code: "AOA", name: "Angolan Kwanza", rateFromUsd: 920 },
  { code: "SZL", name: "Swazi Lilangeni", rateFromUsd: 18.2 },
  { code: "LSL", name: "Lesotho Loti", rateFromUsd: 18.2 },
  { code: "KES", name: "Kenyan Shilling", rateFromUsd: 129 },
  { code: "TZS", name: "Tanzanian Shilling", rateFromUsd: 2600 },
  { code: "UGX", name: "Ugandan Shilling", rateFromUsd: 3700 },
  { code: "RWF", name: "Rwandan Franc", rateFromUsd: 1380 },
  { code: "BIF", name: "Burundian Franc", rateFromUsd: 2900 },
  { code: "DJF", name: "Djiboutian Franc", rateFromUsd: 178 },
  { code: "SOS", name: "Somali Shilling", rateFromUsd: 571 },
  { code: "ETB", name: "Ethiopian Birr", rateFromUsd: 118 },
  { code: "SDG", name: "Sudanese Pound", rateFromUsd: 601 },
  { code: "SSP", name: "South Sudanese Pound", rateFromUsd: 4500 },
  { code: "ERN", name: "Eritrean Nakfa", rateFromUsd: 15 },
  { code: "MGA", name: "Malagasy Ariary", rateFromUsd: 4450 },
  { code: "SCR", name: "Seychellois Rupee", rateFromUsd: 13.6 },
  { code: "MUR", name: "Mauritian Rupee", rateFromUsd: 45.9 },
  { code: "KMF", name: "Comorian Franc", rateFromUsd: 445 },
  { code: "CDF", name: "Congolese Franc", rateFromUsd: 2850 },
  { code: "XCD", name: "East Caribbean Dollar", rateFromUsd: 2.7 },
  { code: "BBD", name: "Barbadian Dollar", rateFromUsd: 2.0 },
  { code: "BSD", name: "Bahamian Dollar", rateFromUsd: 1.0 },
  { code: "BZD", name: "Belize Dollar", rateFromUsd: 2.0 },
  { code: "JMD", name: "Jamaican Dollar", rateFromUsd: 157 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", rateFromUsd: 6.78 },
  { code: "GYD", name: "Guyanese Dollar", rateFromUsd: 209 },
  { code: "SRD", name: "Surinamese Dollar", rateFromUsd: 35.5 },
  { code: "HTG", name: "Haitian Gourde", rateFromUsd: 132 },
  { code: "DOP", name: "Dominican Peso", rateFromUsd: 60.2 },
  { code: "CUP", name: "Cuban Peso", rateFromUsd: 24 },
  { code: "BMD", name: "Bermudian Dollar", rateFromUsd: 1.0 },
  { code: "KYD", name: "Cayman Islands Dollar", rateFromUsd: 0.833 },
  { code: "ANG", name: "Netherlands Antillean Guilder", rateFromUsd: 1.79 },
  { code: "AWG", name: "Aruban Florin", rateFromUsd: 1.79 },
  { code: "FJD", name: "Fijian Dollar", rateFromUsd: 2.27 },
  { code: "PGK", name: "Papua New Guinean Kina", rateFromUsd: 3.95 },
  { code: "SBD", name: "Solomon Islands Dollar", rateFromUsd: 8.55 },
  { code: "VUV", name: "Vanuatu Vatu", rateFromUsd: 120 },
  { code: "WST", name: "Samoan Tala", rateFromUsd: 2.75 },
  { code: "TOP", name: "Tongan Paʻanga", rateFromUsd: 2.36 },
  { code: "PYG", name: "Paraguayan Guarani", rateFromUsd: 7850 },
  { code: "UYU", name: "Uruguayan Peso", rateFromUsd: 40.5 },
  { code: "ARS", name: "Argentine Peso", rateFromUsd: 985 },
  { code: "BOB", name: "Bolivian Boliviano", rateFromUsd: 6.91 },
  { code: "CLP", name: "Chilean Peso", rateFromUsd: 945 },
  { code: "COP", name: "Colombian Peso", rateFromUsd: 4100 },
  { code: "GTQ", name: "Guatemalan Quetzal", rateFromUsd: 7.7 },
  { code: "HNL", name: "Honduran Lempira", rateFromUsd: 24.7 },
  { code: "MXN", name: "Mexican Peso", rateFromUsd: 18.4 },
  { code: "NIO", name: "Nicaraguan Cordoba", rateFromUsd: 36.8 },
  { code: "PAB", name: "Panamanian Balboa", rateFromUsd: 1.0 },
  { code: "PEN", name: "Peruvian Sol", rateFromUsd: 3.75 },
  { code: "VES", name: "Venezuelan Bolivar", rateFromUsd: 40 },
  { code: "BRL", name: "Brazilian Real", rateFromUsd: 5.4 },
  { code: "MOP", name: "Macanese Pataca", rateFromUsd: 8.03 },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", rateFromUsd: 1.8 },
  { code: "MKD", name: "Macedonian Denar", rateFromUsd: 56.5 },
  { code: "ALL", name: "Albanian Lek", rateFromUsd: 92.5 },
  { code: "RSD", name: "Serbian Dinar", rateFromUsd: 108 },
];
