import type { CommissionRule, PartnerLocation } from "./types";

/** Public prospect locations — not claimed AURIX partners. Emails only when commonly published. */
export const SEED_LOCATIONS: PartnerLocation[] = [
  // ——— Saudi Arabia ———
  {
    id: "loc_sa_damas_riyadh",
    partnerId: "p_damas",
    name: "Damas Jewellery — Riyadh Park",
    country: "SA",
    city: "Riyadh",
    type: "chain",
    address: "Riyadh Park Mall, Riyadh",
    lat: 24.7825,
    lng: 46.659,
    website: "https://www.damasjewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.5,
    yearsActive: 40,
    sourceUrl: "https://www.damasjewellery.com/",
    notes: "Regional chain prospect — not an AURIX partner",
  },
  {
    id: "loc_sa_malabar_jeddah",
    partnerId: "p_malabar",
    name: "Malabar Gold & Diamonds — Jeddah",
    country: "SA",
    city: "Jeddah",
    type: "chain",
    address: "Red Sea Mall / Jeddah retail",
    lat: 21.6325,
    lng: 39.156,
    website: "https://www.malabargoldanddiamonds.com/",
    email: "customercare@malabargoldanddiamonds.com",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.4,
    yearsActive: 30,
    sourceUrl: "https://www.malabargoldanddiamonds.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_sa_liali_dammam",
    partnerId: "p_liali",
    name: "Liali Jewellery — Dammam",
    country: "SA",
    city: "Dammam",
    type: "chain",
    address: "Dhahran Mall / Dammam",
    lat: 26.3927,
    lng: 50.1815,
    website: "https://www.liali.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.3,
    yearsActive: 25,
    sourceUrl: "https://www.liali.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_sa_puregold_riyadh",
    partnerId: "p_puregold",
    name: "Pure Gold Jewellers — Riyadh",
    country: "SA",
    city: "Riyadh",
    type: "chain",
    address: "Riyadh Gallery / retail",
    lat: 24.743,
    lng: 46.657,
    website: "https://www.puregold.ae/",
    email: "info@puregold.ae",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.2,
    yearsActive: 20,
    sourceUrl: "https://www.puregold.ae/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_sa_alrajhi_takaful_info",
    partnerId: "p_exchange_sa",
    name: "Al Rajhi Bank — FX / remittance counters (network)",
    country: "SA",
    city: "Riyadh",
    type: "exchange",
    address: "Branch network — Riyadh",
    lat: 24.7136,
    lng: 46.6753,
    website: "https://www.alrajhibank.com.sa/",
    email: "",
    phone: "",
    hours: "Branch hours",
    services: ["pickup", "gold"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.0,
    yearsActive: 50,
    sourceUrl: "https://www.alrajhibank.com.sa/",
    notes: "Bank/FX network prospect — partnership would require formal channel",
  },
  // ——— Egypt ———
  {
    id: "loc_eg_azza_cairo",
    partnerId: "p_azza",
    name: "Azza Fahmy Jewellery — Cairo",
    country: "EG",
    city: "Cairo",
    type: "jewelry",
    address: "Zamalek / City Stars — Cairo",
    lat: 30.0626,
    lng: 31.2197,
    website: "https://azzafahmy.com/",
    email: "info@azzafahmy.com",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "delivery", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.7,
    yearsActive: 40,
    sourceUrl: "https://azzafahmy.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_eg_sami_alex",
    partnerId: "p_sami",
    name: "Sami Jewellery — Alexandria",
    country: "EG",
    city: "Alexandria",
    type: "jewelry",
    address: "Alexandria retail",
    lat: 31.2001,
    lng: 29.9187,
    website: "https://www.sami.com.eg/",
    email: "",
    phone: "",
    hours: "10:00–21:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.1,
    yearsActive: 15,
    sourceUrl: "https://www.sami.com.eg/",
    notes: "Prospect — verify branch; not an AURIX partner",
  },
  {
    id: "loc_eg_gold_souk_khan",
    partnerId: "p_khan",
    name: "Khan El-Khalili Gold District",
    country: "EG",
    city: "Cairo",
    type: "souk",
    address: "Khan El-Khalili, Islamic Cairo",
    lat: 30.0478,
    lng: 31.2625,
    website: "",
    email: "",
    phone: "",
    hours: "Varies by shop",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.0,
    yearsActive: 100,
    sourceUrl: "https://en.wikipedia.org/wiki/Khan_el-Khalili",
    notes: "District of independent shops — recruit individual dealers",
  },
  {
    id: "loc_eg_damas_cairo",
    partnerId: "p_damas",
    name: "Damas Jewellery — Cairo Festival City",
    country: "EG",
    city: "Cairo",
    type: "chain",
    address: "Cairo Festival City Mall",
    lat: 30.028,
    lng: 31.408,
    website: "https://www.damasjewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.4,
    yearsActive: 40,
    sourceUrl: "https://www.damasjewellery.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_eg_egypt_gold",
    partnerId: "p_egypt_gold",
    name: "Egypt Gold",
    country: "EG",
    city: "Cairo",
    type: "bullion",
    address: "Cairo — multiple branches",
    lat: 30.0444,
    lng: 31.2357,
    website: "https://egyptgold.com/",
    email: "info@egyptgold.com",
    phone: "",
    hours: "09:00–21:00",
    services: ["pickup", "delivery", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.3,
    yearsActive: 20,
    sourceUrl: "https://egyptgold.com/",
    notes: "Prospect — not an AURIX partner",
  },
  // ——— Kuwait ———
  {
    id: "loc_kw_behbehani",
    partnerId: "p_behbehani",
    name: "Behbehani Jewellery",
    country: "KW",
    city: "Kuwait City",
    type: "jewelry",
    address: "Kuwait City / Avenues area",
    lat: 29.3759,
    lng: 47.9774,
    website: "https://www.behbehanijewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.5,
    yearsActive: 50,
    sourceUrl: "https://www.behbehanijewellery.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_kw_damas",
    partnerId: "p_damas",
    name: "Damas Jewellery — The Avenues",
    country: "KW",
    city: "Kuwait City",
    type: "chain",
    address: "The Avenues Mall, Kuwait",
    lat: 29.302,
    lng: 47.932,
    website: "https://www.damasjewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.4,
    yearsActive: 40,
    sourceUrl: "https://www.damasjewellery.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_kw_bahrain_exchange",
    partnerId: "p_bahrain_ex",
    name: "Bahrain Exchange Company — Kuwait",
    country: "KW",
    city: "Kuwait City",
    type: "exchange",
    address: "Kuwait City branches",
    lat: 29.3759,
    lng: 47.9774,
    website: "https://www.bahrainexchange.com.kw/",
    email: "",
    phone: "",
    hours: "Branch hours",
    services: ["pickup"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.0,
    yearsActive: 30,
    sourceUrl: "https://www.bahrainexchange.com.kw/",
    notes: "FX/remittance agent prospect",
  },
  {
    id: "loc_kw_liali",
    partnerId: "p_liali",
    name: "Liali Jewellery — Kuwait",
    country: "KW",
    city: "Kuwait City",
    type: "chain",
    address: "Kuwait retail malls",
    lat: 29.3759,
    lng: 47.9774,
    website: "https://www.liali.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.2,
    yearsActive: 25,
    sourceUrl: "https://www.liali.com/",
    notes: "Prospect — not an AURIX partner",
  },
  // ——— UAE ———
  {
    id: "loc_ae_dubai_gold_souk",
    partnerId: "p_dgs",
    name: "Dubai Gold Souk",
    country: "AE",
    city: "Dubai",
    type: "souk",
    address: "Deira Gold Souk, Dubai",
    lat: 25.271,
    lng: 55.298,
    website: "https://www.visitdubai.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.6,
    yearsActive: 50,
    sourceUrl: "https://www.visitdubai.com/en/places-to-visit/gold-souk",
    notes: "Multi-shop district — recruit individual dealers",
  },
  {
    id: "loc_ae_damas_dxb",
    partnerId: "p_damas",
    name: "Damas Jewellery — Dubai Mall",
    country: "AE",
    city: "Dubai",
    type: "chain",
    address: "The Dubai Mall",
    lat: 25.1985,
    lng: 55.2796,
    website: "https://www.damasjewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–24:00",
    services: ["pickup", "delivery", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.5,
    yearsActive: 40,
    sourceUrl: "https://www.damasjewellery.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_ae_malabar_auh",
    partnerId: "p_malabar",
    name: "Malabar Gold & Diamonds — Abu Dhabi",
    country: "AE",
    city: "Abu Dhabi",
    type: "chain",
    address: "Abu Dhabi malls",
    lat: 24.4539,
    lng: 54.3773,
    website: "https://www.malabargoldanddiamonds.com/",
    email: "customercare@malabargoldanddiamonds.com",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.4,
    yearsActive: 30,
    sourceUrl: "https://www.malabargoldanddiamonds.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_ae_joyalukkas_shj",
    partnerId: "p_joy",
    name: "Joyalukkas — Sharjah",
    country: "AE",
    city: "Sharjah",
    type: "chain",
    address: "Sharjah City Centre / retail",
    lat: 25.3463,
    lng: 55.4209,
    website: "https://www.joyalukkas.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.3,
    yearsActive: 30,
    sourceUrl: "https://www.joyalukkas.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_ae_alansari",
    partnerId: "p_alansari",
    name: "Al Ansari Exchange — Dubai",
    country: "AE",
    city: "Dubai",
    type: "exchange",
    address: "Multiple Dubai branches",
    lat: 25.2048,
    lng: 55.2708,
    website: "https://www.alansariexchange.com/",
    email: "",
    phone: "",
    hours: "Branch hours",
    services: ["pickup"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.5,
    yearsActive: 50,
    sourceUrl: "https://www.alansariexchange.com/",
    notes: "Leading FX/remittance agent prospect",
  },
  {
    id: "loc_ae_emirates_gold",
    partnerId: "p_emgold",
    name: "Emirates Gold",
    country: "AE",
    city: "Dubai",
    type: "bullion",
    address: "Dubai — refinery / retail network",
    lat: 25.2048,
    lng: 55.2708,
    website: "https://www.emiratesgold.ae/",
    email: "info@emiratesgold.ae",
    phone: "",
    hours: "By appointment / retail hours",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.6,
    yearsActive: 25,
    sourceUrl: "https://www.emiratesgold.ae/",
    notes: "Bullion/refinery prospect — not an AURIX partner",
  },
  {
    id: "loc_ae_liali_dxb",
    partnerId: "p_liali",
    name: "Liali Jewellery — Dubai",
    country: "AE",
    city: "Dubai",
    type: "chain",
    address: "Dubai malls",
    lat: 25.2048,
    lng: 55.2708,
    website: "https://www.liali.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.3,
    yearsActive: 25,
    sourceUrl: "https://www.liali.com/",
    notes: "Prospect — not an AURIX partner",
  },
  // ——— Qatar ———
  {
    id: "loc_qa_damas_doha",
    partnerId: "p_damas",
    name: "Damas Jewellery — Doha Festival City",
    country: "QA",
    city: "Doha",
    type: "chain",
    address: "Doha Festival City / Place Vendôme",
    lat: 25.2854,
    lng: 51.531,
    website: "https://www.damasjewellery.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.4,
    yearsActive: 40,
    sourceUrl: "https://www.damasjewellery.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_qa_malabar_doha",
    partnerId: "p_malabar",
    name: "Malabar Gold & Diamonds — Doha",
    country: "QA",
    city: "Doha",
    type: "chain",
    address: "Doha retail malls",
    lat: 25.2854,
    lng: 51.531,
    website: "https://www.malabargoldanddiamonds.com/",
    email: "customercare@malabargoldanddiamonds.com",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.3,
    yearsActive: 30,
    sourceUrl: "https://www.malabargoldanddiamonds.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_qa_alfardan",
    partnerId: "p_alfardan",
    name: "Al Fardan Exchange — Doha",
    country: "QA",
    city: "Doha",
    type: "exchange",
    address: "Doha branches",
    lat: 25.2854,
    lng: 51.531,
    website: "https://www.alfardanexchange.com/",
    email: "",
    phone: "",
    hours: "Branch hours",
    services: ["pickup"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.2,
    yearsActive: 40,
    sourceUrl: "https://www.alfardanexchange.com/",
    notes: "FX/remittance agent prospect",
  },
  {
    id: "loc_qa_liali_doha",
    partnerId: "p_liali",
    name: "Liali Jewellery — Doha",
    country: "QA",
    city: "Doha",
    type: "chain",
    address: "Doha malls",
    lat: 25.2854,
    lng: 51.531,
    website: "https://www.liali.com/",
    email: "",
    phone: "",
    hours: "10:00–22:00",
    services: ["pickup", "gold", "silver"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.2,
    yearsActive: 25,
    sourceUrl: "https://www.liali.com/",
    notes: "Prospect — not an AURIX partner",
  },
  {
    id: "loc_qa_gold_souk",
    partnerId: "p_qa_souk",
    name: "Gold Souq — Old Doha",
    country: "QA",
    city: "Doha",
    type: "souk",
    address: "Souq Waqif / Gold Souq area, Doha",
    lat: 25.2867,
    lng: 51.5333,
    website: "",
    email: "",
    phone: "",
    hours: "Varies",
    services: ["pickup", "gold", "silver", "buyback"],
    languages: ["ar", "en"],
    status: "prospect",
    verified: false,
    rating: 4.1,
    yearsActive: 40,
    sourceUrl: "https://www.visitqatar.qa/",
    notes: "District of shops — recruit individual dealers",
  },
];

export const DEFAULT_COMMISSION_RULES: CommissionRule[] = [
  {
    id: "rule_default",
    country: "*",
    partnerType: "*",
    customerFeePct: 3.0,
    partnerFlat: 5,
    partnerSharePct: 35,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rule_sa",
    country: "SA",
    partnerType: "*",
    customerFeePct: 2.8,
    partnerFlat: 6,
    partnerSharePct: 35,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "rule_eg",
    country: "EG",
    partnerType: "*",
    customerFeePct: 3.5,
    partnerFlat: 4,
    partnerSharePct: 40,
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_CROSS_BORDER_LIVE: Record<string, boolean> = {
  "SA-EG": false,
  "AE-EG": false,
  "KW-EG": false,
  "QA-EG": false,
  "AE-SA": false,
  "SA-AE": false,
};
